# Generated by Django 5.1.5 on 2025-02-02 06:28

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='English question')),
                ('answer', ckeditor.fields.RichTextField(help_text='Answer in English (with rich text)')),
                ('question_hi', models.TextField(blank=True, help_text='Hindi translation', null=True)),
                ('question_bn', models.TextField(blank=True, help_text='Bengali translation', null=True)),
            ],
        ),
    ]
